# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pacote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacote',
            name='qtd',
        ),
        migrations.AddField(
            model_name='adquirente',
            name='qtd',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
