# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171001_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='adquirente',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
